version: "3.3"
services:
    web:
        build: .
        entrypoint: ./entrypoint.sh
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            - db
    
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
volumes:
  web:
  pgdata:
